### ISSUE TITLE
redis connection isn't being closed properly

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_corr_cm#10]
leads to this (from qmaster:/var/log/syslog):
```
Dec 14 19:02:38 qmaster systemd[1]: Started Cleanup of Temporary Directories.
Dec 14 19:03:08 qmaster mc_monitor_correlator.py[9957]: Fri Dec 14 19:03:08 2018 -- error adding correlator control state
Dec 14 19:03:08 qmaster mc_monitor_correlator.py[9957]: Traceback (most recent call last):
Dec 14 19:03:08 qmaster mc_monitor_correlator.py[9957]:   File "/home/obs/anaconda/envs/HERA/bin/mc_monitor_correlator.py", line 30, in <module>
Dec 14 19:03:08 qmaster mc_monitor_correlator.py[9957]:   File "/home/obs/anaconda/envs/HERA/lib/python2.7/site-packages/hera_mc/mc_session.py", line 1445, in add_correlator_control_state_from_corrcm
Dec 14 19:03:08 qmaster mc_monitor_correlator.py[9957]:   File "/home/obs/anaconda/envs/HERA/lib/python2.7/site-packages/hera_mc/correlator.py", line 99, in _get_control_state
Dec 14 19:03:08 qmaster mc_monitor_correlator.py[9957]:   File "/home/obs/anaconda/envs/HERA/lib/python2.7/site-packages/hera_corr_cm/hera_corr_cm.py", line 37, in __init__
Dec 14 19:03:08 qmaster mc_monitor_correlator.py[9957]:   File "/home/obs/anaconda/envs/HERA/lib/python2.7/site-packages/redis/client.py", line 2482, in subscribe
Dec 14 19:03:08 qmaster mc_monitor_correlator.py[9957]:   File "/home/obs/anaconda/envs/HERA/lib/python2.7/site-packages/redis/client.py", line 2404, in execute_command
Dec 14 19:03:08 qmaster mc_monitor_correlator.py[9957]:   File "/home/obs/anaconda/envs/HERA/lib/python2.7/site-packages/redis/client.py", line 2415, in _execute
Dec 14 19:03:08 qmaster mc_monitor_correlator.py[9957]:   File "/home/obs/anaconda/envs/HERA/lib/python2.7/site-packages/redis/connection.py", line 489, in connect
Dec 14 19:03:08 qmaster mc_monitor_correlator.py[9957]: ConnectionError: Error 24 connecting to redishost:6379. Too many open files.
Dec 14 19:04:08 qmaster mc_monitor_correlator.py[9957]: Fri Dec 14 19:04:08 2018 -- error adding correlator control state
Dec 14 19:04:08 qmaster mc_monitor_correlator.py[9957]: Traceback (most recent call last):
Dec 14 19:04:08 qmaster mc_monitor_correlator.py[9957]:   File "/home/obs/anaconda/envs/HERA/bin/mc_monitor_correlator.py", line 30, in <module>
Dec 14 19:04:08 qmaster mc_monitor_correlator.py[9957]:   File "/home/obs/anaconda/envs/HERA/lib/python2.7/site-packages/hera_mc/mc_session.py", line 1445, in add_correlator_control_state_from_corrcm
Dec 14 19:04:08 qmaster mc_monitor_correlator.py[9957]:   File "/home/obs/anaconda/envs/HERA/lib/python2.7/site-packages/hera_mc/correlator.py", line 99, in _get_control_state
Dec 14 19:04:08 qmaster mc_monitor_correlator.py[9957]:   File "/home/obs/anaconda/envs/HERA/lib/python2.7/site-packages/hera_corr_cm/hera_corr_cm.py", line 37, in __init__
Dec 14 19:04:08 qmaster mc_monitor_correlator.py[9957]:   File "/home/obs/anaconda/envs/HERA/lib/python2.7/site-packages/redis/client.py", line 2482, in subscribe
Dec 14 19:04:08 qmaster mc_monitor_correlator.py[9957]:   File "/home/obs/anaconda/envs/HERA/lib/python2.7/site-packages/redis/client.py", line 2404, in execute_command
Dec 14 19:04:08 qmaster mc_monitor_correlator.py[9957]:   File "/home/obs/anaconda/envs/HERA/lib/python2.7/site-packages/redis/client.py", line 2415, in _execute
Dec 14 19:04:08 qmaster mc_monitor_correlator.py[9957]:   File "/home/obs/anaconda/envs/HERA/lib/python2.7/site-packages/redis/connection.py", line 489, in connect
Dec 14 19:04:08 qmaster mc_monitor_correlator.py[9957]: ConnectionError: Error 24 connecting to redishost:6379. Too many open files.
Dec 14 19:04:27 qmaster systemd[1]: Started Session 41316 of user obs.
Dec 14 19:04:35 qmaster systemd[1]: Started Session 41317 of user obs.
Dec 14 19:05:01 qmaster CRON[29278]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)```

**Comment by jack-h** [comment]
Commit 96f03bf should resolve this, hopefully.

**Comment by bhazelton** [comment]
This is fixed (has been for awhile).
